name: Deploy to Digitalocean

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy BadBank App
              uses: appleboy/ssh-action@v0.1.3
              with:
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}
                  username: ${{secrets.SSH_USERNAME}}

                  script: |
                      if [ ! -d badbank ]
                      then
                          mkdir badbank
                          cd badbank
                          git clone git@github.com:chatojavier/badbank.git
                          docker-compose up
                          echo "Deployment succesfull to Digital Ocean"
                      else
                          cd badbank
                          git pull origin main
                          docker-compose pull badbank-app
                          docker-compose up --detach
                          echo "Deployment succesfull to Digital Ocean"
                      fi
